-- Refund & Cancellation Policy, Delivery Policy and Contact Us pages (needed for payment
-- gateway approval), editable from the admin panel like Terms/Privacy.
-- {business_name}, {contact_email} and {contact_phone} in these texts are filled in by
-- the website from the matching settings, so they only need changing in one place.
-- This is a working draft, not legal advice — review before relying on it.
insert into public.settings (key, value) values
  ('business_name', 'Sounds Of Heaven Music Institute (Proprietor: Dheeraj Kumar Malviya)'),
  ('business_address', ''),
  ('refund_text', E'This Refund & Cancellation Policy applies to all books and podcasts sold on King''s Library (kingslibrary.online), operated by {business_name}.\n\n<strong>Digital content — no refunds once delivered.</strong> Everything we sell is digital and can be read or listened to as soon as access is delivered. For this reason, all sales are final once access has been delivered, and we do not offer refunds for a change of mind or for content that has already been delivered.\n\n<strong>When you are entitled to a full refund.</strong> We will refund the full amount if: (1) you were charged but did not receive access, and we could not fix this within 48 hours of you contacting us; (2) you were charged more than once for the same book or podcast; (3) you were charged an amount different from the price shown on the website; or (4) the book or podcast you bought is missing, cannot be opened, or is materially different from its description, and we could not fix this within 7 days of you reporting it.\n\n<strong>How to request a refund.</strong> Email us at {contact_email} or call {contact_phone} within 7 days of your purchase. Please include the email address you used for the purchase, the title you bought, and your payment reference (for example, the UPI transaction ID or payment ID). We will reply within 2 working days.\n\n<strong>Refund timeline.</strong> Approved refunds are made to the original payment method (UPI, card, net banking or wallet). Once we process the refund, the money usually reaches your account within 5–7 working days, depending on your bank.\n\n<strong>Cancellations.</strong> Because access is delivered digitally, soon after payment, an order cannot be cancelled once payment is complete. If you were charged by mistake, see "When you are entitled to a full refund" above. When a refund is issued, access to that book or podcast is removed from your account.\n\n<strong>Contact.</strong> For any question about this policy, contact {business_name} at {contact_email} or {contact_phone}.'),
  ('delivery_text', E'This Delivery Policy explains how you receive the books and podcasts you buy on King''s Library (kingslibrary.online), operated by {business_name}.\n\n<strong>Digital delivery only.</strong> All our products are digital: books you read and podcasts you listen to inside the King''s Library app, in your web browser on your phone, tablet or computer. Nothing is shipped physically, and there are no shipping charges. Delivery is available wherever you have an internet connection.\n\n<strong>How access is delivered.</strong> Once your payment is confirmed, the book or podcast is added to your King''s Library account and we send an email to the address you gave when buying, with a link to the app. Open the link and sign in with that same email address — we send you a one-time code, so there is no password to remember. Your purchase will be waiting in your library.\n\n<strong>Delivery time.</strong> Access is usually delivered by email within minutes of a successful payment. In rare cases — for example, if your bank takes longer to confirm the payment, or you paid us directly instead of through the website — it can take up to 24 hours.\n\n<strong>Didn''t receive it?</strong> First check your spam or promotions folder for an email from King''s Library. If it isn''t there, contact us at {contact_email} or {contact_phone} with the email address you used and your payment reference, and we will sort it out within 1 working day. If we cannot deliver your purchase, you are entitled to a full refund under our Refund & Cancellation Policy.')
on conflict (key) do nothing;

-- The Terms' old refund sentence ("case-by-case") now contradicts the Refund policy —
-- point to the policy instead. Only changes the text if it is still the original draft.
update public.settings
set value = replace(value,
  'Because access is granted individually after purchase, refund requests are handled on a case-by-case basis — contact us directly to discuss any issue with your purchase.',
  'Refunds and cancellations are covered by our Refund & Cancellation Policy, linked at the bottom of every page.')
where key = 'terms_text';
